# Generated by Django 3.0.5 on 2020-04-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('pbr', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('availabel', models.CharField(max_length=15)),
            ],
        ),
    ]
