# Generated by Django 3.0.5 on 2020-04-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='availabel',
        ),
    ]
