# Generated by Django 3.0.5 on 2020-04-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0003_brmuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brmuser',
            old_name='nickname',
            new_name='member_id',
        ),
    ]
