# Generated by Django 3.2 on 2021-04-24 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0004_auto_20200421_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brmuser',
            old_name='member_id',
            new_name='member_Id',
        ),
        migrations.AddField(
            model_name='brmuser',
            name='mobile_num',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
