# Generated by Django 3.2 on 2021-04-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0005_auto_20210425_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brmuser',
            name='mobile_num',
        ),
    ]
