# Generated by Django 3.2 on 2021-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0006_remove_brmuser_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='brmuser',
            name='mobile_num',
            field=models.IntegerField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
