# Generated by Django 3.2 on 2021-04-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BRMapp', '0007_brmuser_mobile_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brmuser',
            name='mobile_num',
        ),
    ]
